version: "3.2"

services:
  dev:
    image: pacific-store-node
    working_dir: /var/www/pacific-store
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/pacific-store/.cargo
    volumes:
      - .:/var/www/pacific-store
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/pacific-store --dev --ws-external"
